/** SQLite DDL — every business table includes id (UUID), updated_at, sync_status. */

export const SYNC_STATUS = {
  PENDING: "PENDING",
  SYNCED: "SYNCED",
  FAILED: "FAILED",
};

export const SCHEMA_VERSION = 6;

export const CREATE_TABLES_SQL = [
  `CREATE TABLE IF NOT EXISTS app_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'SYNCED'
  )`,
  `CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    lot_number TEXT,
    expiration_date TEXT,
    price REAL NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,
  `CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    email TEXT,
    tax_number TEXT,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,
  `CREATE TABLE IF NOT EXISTS suppliers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,
  `CREATE TABLE IF NOT EXISTS sales (
    id TEXT PRIMARY KEY,
    invoice_number TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    status TEXT NOT NULL,
    receipt_type TEXT NOT NULL,
    transaction_type TEXT NOT NULL,
    sdc_receipt_code TEXT NOT NULL,
    copy_index INTEGER NOT NULL DEFAULT 0,
    method TEXT,
    method_label TEXT,
    total_usd REAL NOT NULL,
    total_cdf REAL NOT NULL,
    change_due_usd REAL DEFAULT 0,
    amount_received REAL,
    reference TEXT,
    card_last_four TEXT,
    cashier_id TEXT,
    cashier_name TEXT,
    customer_id TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    customer_address TEXT,
    customer_email TEXT,
    customer_tax_number TEXT,
    exchange_rate REAL,
    refund_at TEXT,
    refund_reason TEXT,
    refund_restore_stock INTEGER,
    refund_by_user_id TEXT,
    refund_by_user_name TEXT,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,
  `CREATE TABLE IF NOT EXISTS sale_items (
    id TEXT PRIMARY KEY,
    sale_id TEXT NOT NULL,
    product_id TEXT,
    name TEXT NOT NULL,
    lot_number TEXT,
    expiration_date TEXT,
    price REAL NOT NULL,
    qty INTEGER NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS purchase_orders (
    id TEXT PRIMARY KEY,
    supplier_id TEXT,
    supplier_name TEXT NOT NULL,
    supplier_phone TEXT,
    supplier_address TEXT,
    reference TEXT,
    notes TEXT,
    total_cost REAL NOT NULL DEFAULT 0,
    timestamp TEXT NOT NULL,
    created_by_user_id TEXT,
    created_by_user_name TEXT,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,
  `CREATE TABLE IF NOT EXISTS purchase_items (
    id TEXT PRIMARY KEY,
    purchase_id TEXT NOT NULL,
    product_id TEXT,
    product_name TEXT NOT NULL,
    lot_number TEXT,
    expiration_date TEXT,
    unit_cost REAL NOT NULL DEFAULT 0,
    qty INTEGER NOT NULL,
    line_total REAL NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY (purchase_id) REFERENCES purchase_orders(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,
  `CREATE TABLE IF NOT EXISTS stock_snapshots (
    id TEXT PRIMARY KEY,
    snapshot_date TEXT NOT NULL,
    snapshot_month TEXT NOT NULL,
    product_id TEXT NOT NULL,
    product_name TEXT NOT NULL,
    lot_number TEXT,
    expiration_date TEXT,
    price REAL NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    stock_value REAL NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'PENDING',
    UNIQUE(snapshot_date, product_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sales_timestamp ON sales(timestamp DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_sales_sync ON sales(sync_status)`,
  `CREATE INDEX IF NOT EXISTS idx_products_sync ON products(sync_status)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_sync ON customers(sync_status)`,
  `CREATE INDEX IF NOT EXISTS idx_suppliers_sync ON suppliers(sync_status)`,
  `CREATE INDEX IF NOT EXISTS idx_purchase_orders_timestamp ON purchase_orders(timestamp DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_purchase_orders_sync ON purchase_orders(sync_status)`,
  `CREATE INDEX IF NOT EXISTS idx_stock_snapshots_date ON stock_snapshots(snapshot_date DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_stock_snapshots_month ON stock_snapshots(snapshot_month DESC)`,
  `CREATE TABLE IF NOT EXISTS operators (
    id TEXT PRIMARY KEY,
    merchant_code TEXT NOT NULL,
    branch_code TEXT,
    username TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    credentials_version INTEGER NOT NULL DEFAULT 1,
    synced_at TEXT NOT NULL,
    UNIQUE (merchant_code, username)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_operators_merchant ON operators(merchant_code)`,
];
